function settings = makeDefaultSettings()
settings = struct();
settings.speed = 400;
settings.sizeX = 100;
settings.sizeY = 100;
settings.useLearningRate = 0;
settings.learningRateMean = .9;
settings.learningRateSD = .05;
settings.useTemperature = 0;
settings.temperature = 0;
settings.flippedNoise = 1;
settings.synchronous = 0;
settings.imageLibLoc = './image_library';
settings.stopOnMatch = 1;
settings.pMatch = 99.9;